services:

  app:
    container_name: time_tracker
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped
   

  postgres:
    container_name: time_tracker_pgdb
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg-data:
